apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflow-template-example
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: busybox
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/DavidR0/argowf-test # Replace with your repo URL
    targetRevision: HEAD
    path: . # Path where your WorkflowTemplate YAML is stored
  destination:
    server: https://kubernetes.default.svc
    namespace: argo # Namespace where Argo Workflows is installed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
