apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-test-image
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: busybox=busybox:^1.37.0
    argocd-image-updater.argoproj.io/update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
    # argocd-image-updater.argoproj.io/force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/DavidR0/argowf-test # Replace with your repo URL
    targetRevision: main
    path: . # Path where your WorkflowTemplate YAML is stored
  destination:
    server: https://kubernetes.default.svc
    namespace: argo # Namespace where Argo Workflows is installed
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
